### ISSUE TITLE
No account creation confirmation message

### ISSUE THREAD

**Issue by LucileDT** [AAAsso/succube-sarl#12]
### Page
Account creation

### Scenario
- create an account

### Expected behaviour
- redirection to the home page
- message explaining that the creation worked
- automated connection with the created account

### Current behaviour
- redirection to the home page

**Comment by LucileDT** [comment]
- [x] add a 'info' message displayed with alerts (same than the one we get when the username/password is incorrect)
- [x] connect the user using the created account

**Comment by V-Tommy** [comment]
@DarckCrystale Let's go testing :)

**Comment by LucileDT** [comment]
Works well!
