### ISSUE TITLE
Edition of parameters of a user accessible from another user

### ISSUE THREAD

**Issue by LucileDT** [AAAsso/succube-sarl#13]
### Page
Edition of a user's information

### Scenario
- Connect with user A
- Got to the user B edition page

### Expected behaviour
- Redirection to home page
- Display of an error "you can't do this"

### Current behaviour
- Edition of user B is possible from user A

**Comment by V-Tommy** [comment]
@DarckCrystale Need you to test it :)

**Comment by LucileDT** [comment]
@hundrex new usecase:
- as an admin, I want to edit a profile (because the username is problematic for example).

- [x] admin able to edit the profile of someone else

**Comment by V-Tommy** [comment]
@DarckCrystale Done, you can test it !

**Comment by LucileDT** [comment]
- [x] with a not connected user, display a big error

![image](https://user-images.githubusercontent.com/23707217/35383991-37d45864-01c4-11e8-93ca-19c42e53f9ee.png)

**Comment by V-Tommy** [comment]
This problem also affects every other check for an admin account I made. It will be corrected in next commit for this issue.

**Comment by V-Tommy** [comment]
Done, you can test it @DarckCrystale

**Comment by LucileDT** [comment]
It works.
