### ISSUE TITLE
Edition of password of a user needs to check old password

### ISSUE THREAD

**Issue by LucileDT** [AAAsso/succube-sarl#14]
### Page
Edition of a user

### Scenario
- Edit password

### Expected behaviour
- Form asks you to enter your old password

### Current behaviour
- No old password needed.

**Comment by LucileDT** [comment]
Seems to be corrected by a8822f03dfcca80a2fc4d2cc90cc976bab2718b7
@hundrex could you check this?

**Comment by DarckCrystale** [comment]
![image](https://user-images.githubusercontent.com/13867472/57516938-04e37100-7316-11e9-9c58-a8726c1cdfe4.png)


The edition page looks like this.
