### ISSUE TITLE
Need a home button/link

### ISSUE THREAD

**Issue by V-Tommy** [AAAsso/succube-sarl#24]
### Page
base.html.twig

### Scenario
There is no way to go back to home page when navigating.

### Expected behaviour
A button somewhere and/or the logo linked to the home page.

### Current behaviour
Nothing is linked to home page, we have to get there manualy.

**Comment by LucileDT** [comment]
![image](https://user-images.githubusercontent.com/23707217/34868863-70539b3a-f785-11e7-87f7-1b9801174423.png)
See the `Last strip` button added in #22 :P

**Comment by LucileDT** [comment]
You're right, a link would be cool on the header like here:
![image](https://user-images.githubusercontent.com/23707217/34868992-d39f9cd4-f785-11e7-881f-539511b649dc.png)
@DarckCrystale please!

**Comment by V-Tommy** [comment]
Last strip is not a pertinent name for home link, but the header link would be great.

**Comment by LucileDT** [comment]
@hundrex could you test this please?

**Comment by V-Tommy** [comment]
This is great
