### ISSUE TITLE
Edition of user should encrypt new password

### ISSUE THREAD

**Issue by V-Tommy** [AAAsso/succube-sarl#27]
### Page
Edition of a user

### Scenario
- Edit password

### Expected behaviour
- Plain password given by the user must be encrypted then stored in database

### Current behaviour
- Password stored in plain text

Related to #14

**Comment by LucileDT** [comment]
Seems to be corrected by a8822f03dfcca80a2fc4d2cc90cc976bab2718b7
@hundrex could you check this?
