### ISSUE TITLE
CRUD CW

### ISSUE THREAD

**Issue by LucileDT** [AAAsso/succube-sarl#28]
- [x] CRUD of a Content Warning
  - [x] Create
  - [x] Show
  - [x] Edit
  - [x] List
  - [x] Delete

- [x] Content Warning
  - [x] id `int`
  - [x] label `string`
  - [x] description `string`

**Comment by V-Tommy** [comment]
@DarckCrystale Can you test it please ?

**Comment by LucileDT** [comment]
Need front end for 
- [x] create
- [x] show
- [x] admin show
- [x] edit
- [x] list
- [x] delete
  - [x] from list
  - [x] from edit

**Comment by LucileDT** [comment]
- [x] Only admin can access
  - [x] edit
  - [x] list
  - [x] admin show
  - [x] delete
  - [x] create

**Comment by LucileDT** [comment]
@hundrex all skins have been done could you check this issue?
