### ISSUE TITLE
Main page and top menu layout

### ISSUE THREAD

**Issue by LucileDT** [AAAsso/succube-sarl#3]
Light theme
- [x] top menu
- [x] main page
  - [x] title
  - [x] strip
  - [x] navigation top
  - [x] navigation bottom
- [x] bottom nav bar

**Comment by LucileDT** [comment]
See 4903b08f29500c3e14d64e4c3cd186cede692980 for top menu and footer

**Comment by LucileDT** [comment]
As the SFW/NSFW will be developed in another version, I create a specific issue (#17) for it and remove the item of the list in this issue.

**Comment by LucileDT** [comment]
@hundrex could you please check the items of the list?
If something goes wrong, could you create an issue describing it?

**Light theme**
- [x] top menu
- [x] main page
  - [x] title
  - [x] strip
  - [x] navigation top
  - [x] navigation bottom
- [x] bottom nav bar

Thx!

**Comment by V-Tommy** [comment]
Done !
