### ISSUE TITLE
List of accounts openable by non admin users

### ISSUE THREAD

**Issue by LucileDT** [AAAsso/succube-sarl#30]
### Page
List of all accounts

### Scenario
- Connect with a Guest user or a User
- Got to the account list page (`/admin/accounts`)

### Expected behaviour
- Redirection to home page
- Display of an error "you can't do this"

### Current behaviour
- Page is visible

**Comment by V-Tommy** [comment]
Has been solved in 661a478 but I forgot to tell it in the commit message. To be tested please @DarckCrystale

**Comment by LucileDT** [comment]
It works, perfect :ok_hand:
