### ISSUE TITLE
Need to reload page when using Account edition forms

### ISSUE THREAD

**Issue by V-Tommy** [AAAsso/succube-sarl#34]
### Page
Account edit

### Scenario
- Change username
- Save new username
- Change password
- Save new password

### Expected behaviour
- Password is updated

### Current behaviour
- Page throws an error (add screenshot)

### Comment
*If using the Password change form after updating the username with the Account Edit form, it doesn't work because it tries to change the password of the ancient username account, wich doesn't exist anymore.*

**Comment by LucileDT** [comment]
It will be solved by #40.

**Comment by LucileDT** [comment]
@hundrex this has been done, could you test it please?
