### ISSUE TITLE
User account dropdown in navbar throwing error if used after changing username

### ISSUE THREAD

**Issue by V-Tommy** [AAAsso/succube-sarl#35]
### Page
Any

### Scenario
- Change username in Account Edit
- Try to use the account dropdown navbar links My profile or Preferences

### Expected behaviour
- Redirecting to asked page (My profile or Preferences)

### Current behaviour
- Throws error because it tries to redirect to the pages of the ancient username, wich doesn't exist anymore

**Comment by LucileDT** [comment]
It will be solved by #40.

**Comment by LucileDT** [comment]
@hundrex this has been done, could you test it please?
