### ISSUE TITLE
ContentWarning <-> strips mapping is incorrect

### ISSUE THREAD

**Issue by LucileDT** [AAAsso/succube-sarl#47]
### Page
List of all content warnings (/admin/content-warnings)

### Scenario
- go to the page

### Expected behaviour
- no problem displaying, no errors in Symfony Profiler

### Current behaviour
- Error in Symfony profiler

![image](https://user-images.githubusercontent.com/23707217/36321408-13f0fcf8-134a-11e8-8e68-00e27182ddb3.png)

![image](https://user-images.githubusercontent.com/23707217/36321434-21414dae-134a-11e8-9a4d-4020712bc0e9.png)

**Comment by V-Tommy** [comment]
@DarckCrystale You can test it

**Comment by LucileDT** [comment]
Been solved!
