### ISSUE TITLE
Gestion des comptes utilisateur

### ISSUE THREAD

**Issue by LucileDT** [AAAsso/succube-sarl#5]
- [x] connexion
- [x] deconnexion

**Comment by V-Tommy** [comment]
**Penser pour la sécu à changer les messages de logins après les tests afin que l'on ne puisse pas savoir qui du couple login/password est incorrect, et qu'on ne divulgue pas si le login entré existe ou non**

**Comment by LucileDT** [comment]
@Parmifer

**Comment by V-Tommy** [comment]
J'ai fini. A vérifier.

**Comment by LucileDT** [comment]
It works
