### ISSUE TITLE
CRUD of users

### ISSUE THREAD

**Issue by LucileDT** [AAAsso/succube-sarl#8]
- [x] pages
    - [x] create
    - [x] show details
    - [x] update details
    - [x] list users
    - [x] delete
- [x] menu
    - [x] manage users = table with all the users, each row with a button to delete and a button to see the details
    - [x] my account > preferences = update details

**Comment by LucileDT** [comment]
@DarckCrystale 
Please edit style of
- [x] details of an account (/account/username)
- [x] edit information (/account/edit/username)

**Comment by LucileDT** [comment]
@DarckCrystale 
Please add a link to the 
- [x] create an account form (/account/new)
under the connection form

**Comment by LucileDT** [comment]
@DarckCrystale please add a dropdown in the navbar:
- [x] dropdown `Administration`
  - [x] link `Manage users`

It should be displayed only if user has admins rights.

**Comment by LucileDT** [comment]
@DarckCrystale creation page is borken.

**Comment by LucileDT** [comment]
@hundrex all of it works, can you check it?

**Comment by V-Tommy** [comment]
Closing but some bugs need to be corrected, I created issues for them.
